[package]
authors    =["Pluto Authors"]
description="""ronkathon"""
edition    ="2021"
license    ="Apache2.0 OR MIT"
name       ="ronkathon"
repository ="https://github.com/thor314/ronkathon"
version    ="0.1.0"

[dependencies]
anyhow   ="1.0"
p3-field = { path = "../field" }
